### ISSUE TITLE
How to connect Serverless(offline) function with Kinesalite streams

### ISSUE THREAD

**Issue by tareq89** [mhart/kinesalite#47]
I have created a stream with kinesalite. I have run putRecords, getRecords operation through http rest api. 

Now If I want to connect this stream event with my Serverless nodejs app, how do I do that? note that I am running everything locally, serverless uses serverless-offline.

The kinesalite service is running on localhost:4567. How do I add event in my serverless.yml file so that my function can read stream events?

Currently I am writing something like this.
```
stream:
    handler: functions/stream.handler
    events:
      - stream:
          arn: arn:aws:kinesis:region:us-east-1:stream/stream1
          batchSize: 100
          startingPosition: LATEST
          enabled: true
```
